<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headTitle()->prepend($this->translate('Installation - Step ') . 2); ?>
<div id="installation">
	<h1><?php echo $this->translate('Joobsbox installation complete!'); ?></h1>
	<p>
		<?php echo $this->translate('Congratulations. You finished installing Joobsbox. Now please configure your administrator username and password.'); ?>
		<?php echo $this->form; ?>
	</p>
</div>
