<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headTitle()->prepend($this->translate('Installation - Step ') . 1); ?>
<div id="installation">
	<h1><?php echo $this->translate('Welcome to Joobsbox installation!'); ?></h1>
	<p>
	<?php echo $this->translate('I need some information and then we\'re ready to go.'); ?><br/>
	
	<?php echo $this->mainForm; ?>
	
	<?php if(isset($this->dberror)): ?>
	<div class="fieldpair error">
	<?php echo $this->dberror; ?>
	</div>
	<?php endif; ?>
	</p>
</div>
