<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headTitle($this->translate("Job search") . ': ' . $this->searchedString); ?>
	<div class="list">
		<div class="inner">
			<a href="#">
				<?php echo $this->translate("Search") . ': ' . $this->searchedString; ?>
			</a>
		</div>
		  <?php if(count($this->jobs)): ?>
			<ul>
				<?php foreach($this->jobs as $a => $job): ?>
				<li <?php if($a%2):?>class="alternate"<?php endif;?>>
					<a href="<?php echo $this->baseUrl;?>/job/<?php echo $this->MakeLink($job['Title']) . "-" . $job['ID']; ?>.html"><?php echo $this->filter("job_title", $job['Title']); ?></a>
					<span class="lighterSmall"> <?php echo $this->translate("at"); ?> </span>
					<?php echo $this->filter("job_company", $job['Company']); ?>
					<span class="lighterSmall"> <?php echo $this->translate("in"); ?> </span>
					<?php echo $this->filter("job_location", $job['Location']); ?>
				</li>
				<?php endforeach; ?>
			</ul>
			<?php else: ?>
			  <div class="info"><?php echo $this->translate('Nothing to be found for your searched criteria.'); ?></div>
        <ul>
          <li><?php echo $this->translate('Look for typos in the searched word(s) and, if found, correct them.'); ?></li>
          <li><?php echo $this->translate('Be less specific. Try "web designer" instead of "senior web designer".'); ?></li>
          <li><?php echo $this->translate('Try similar words. If "designer" doesn\'t return anything, try "design".'); ?></li>
        </ul>        
		  <?php endif; ?>
	</div>
