<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<div>
	<?php $this->headTitle($this->translate("Administration Dashboard")); ?>
	<ul id="plugins">
		<?php foreach($this->plugins as $pluginName => $pluginOptions): ?>
		<li class="plugin">
			<a href="<?php echo $this->baseUrl . strtolower("/admin/$pluginName"); ?>">
				<img class="pluginImage" src="<?php if($pluginOptions->main->image): echo $this->pluginPath . $pluginOptions->main->image; else: echo $this->themeImages . '/adminPluginNoImage.jpg'; endif;?>" /><br/>
				<span class="pluginTitle">
					<?php 
						if($pluginOptions->main->{"title_" . $this->locale}) {
							echo ucfirst($pluginOptions->main->{"title_" . $this->locale});
						} elseif($pluginOptions->main->title) {
							echo ucfirst($pluginOptions->main->title);
						} else {
							echo ucfirst($pluginName); 
						}
					?>
				</span>
			</a>
		</li>
		<?php endforeach; ?>
		<li class="clearer"></li>
	</ul>
</div>

<?php
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/admin.css");
	$this->headScript()->appendFile($this->themeUrl . '/js/admin.js', 'text/javascript')
?>