<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<h2><?php echo $this->message ?></h2> 

<?php if ($this->dev): ?> 
    <h3>Exception information:</h3> 
    <p> 
        <b>Message:</b> <?php echo $this->exception->getMessage(); ?> 
    </p> 

    <h3>Stack trace:</h3> 
    <pre><?php echo $this->exception->getTraceAsString() ?></pre> 

    <h3>Request Parameters:</h3> 
    <pre><?php var_dump($this->request->getParams()) ?></pre> 
<?php endif ?>
