<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headTitle(
	$this->filter("job_title", $this->job['Title']) . ' ' .
	$this->translate("at") . ' ' .
	$this->filter("job_company", $this->job['Company']) . ' ' .
	$this->translate("in") . ' ' .
	$this->filter("job_location", $this->job['Location']),
	'PREPEND'
); ?>
<div class="inner">
	<strong>
		<?php echo $this->filter("job_title", $this->job['title']); ?>
		<span class="lighterSmall"> <?php echo $this->translate("at"); ?> </span>
		<?php echo $this->filter("job_company", $this->job['company']); ?>
		<span class="lighterSmall"> <?php echo $this->translate("in"); ?> </span>
		<?php echo $this->filter("job_location", $this->job['location']); ?>
	</strong>
</div>
<div id="jobContent">
	<h2><?php echo $this->translate("Description:"); ?></h2>
	<?php echo $this->filter("job_description", $this->job['description']); ?>
	<h2><?php echo $this->translate("To apply:"); ?></h2>
	<?php echo $this->filter("job_application_method", $this->job['toapply']); ?>
</div>
