<?php $this->headTitle($this->translate("Job search")); ?>
	<div class="list">
		<div class="inner">
			<a href="#">
				<?php echo $this->translate("Search"); ?>
			</a>
		</div>
			<ul>
				<?php foreach($this->jobs as $a => $job): ?>
				<li <?php if($a%2):?>class="alternate"<?php endif;?>>
					<a href="<?php echo $this->baseUrl;?>/job/<?php echo $this->MakeLink($job['Title']) . "-" . $job['ID']; ?>.html"><?php echo $this->filter("job_title", $job['Title']); ?></a>
					<span class="lighterSmall"> <?php echo $this->translate("at"); ?> </span>
					<?php echo $this->filter("job_company", $job['Company']); ?>
					<span class="lighterSmall"> <?php echo $this->translate("in"); ?> </span>
					<?php echo $this->filter("job_location", $job['Location']); ?>
				</li>
				<?php endforeach; ?>
			</ul>
	</div>