<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JoobsboxMigration extends Doctrine_Migration_Base
{
    public function up()
    {

    }

    public function down()
    {

    }
}