<h1 class="dashboard-title"><?php echo $this->translate("Categories"); ?></h1>
<div id="tree-controls">
	<a id="createNewNode"><?php echo $this->translate('Create category'); ?></a>
	<a id="deleteNode"><?php echo $this->translate('Delete category'); ?></a>
	<a id="saveConfiguration"><?php echo $this->translate("Save"); ?></a>
	<span id="info">&nbsp;</span>
	<div style="clear:both"></div>
</div>

<?php /* 
<div id="categ-wrapper">
	<ul>
		<li id="node_root" class="open" rel="root">
			<a href="#"><?php echo $this->translate('Categories'); ?></a>
			<?php if(count($this->categories->filterRootNodes())): ?>
			<ul>
				<?php foreach($this->categories->filterRootNodes() as $category): ?>

							<li id="node_<?php echo $category['ID']; ?>" rel="primary-categ">
								<a href="#" class="editable"><?php echo $category['Name']; ?></a>
				<?php 			$children = $category->getChildren();
								if(count($children)): 										?>
									<ul>
				<?php 				foreach($children as $child):							?>
										<li id="node_<?php echo $child['ID']; ?>" rel="secondary-categ">
											<a href="#"><?php echo $child['Name']; ?></a>
										</li>
				<?php				endforeach;												?>
									</ul>
				<?php 			endif; 														?>
							</li>
				<?php endforeach; 													?>
			</ul>
			<?php endif; ?>
		</li>
	</ul>
</div>
 */ ?>
 
<div id="categ-wrapper">
  <ul id="categories">
    <?php foreach($this->categories->filterRootNodes() as $index => $category): ?>
		<li class="editable" id="existing_<?php echo $category['id']; ?>"><?php echo $category['name']; ?></li>
		<?php endforeach; ?>
  </ul>
</div>

<div id="instructions">
	<h2><?php echo $this->translate('Instructions'); ?></h2>
	<p>
		<?php echo $this->translate(
			'To reorder categories, simply drag and drop them.<br/>
			To create a new category, click "Create category".<br/>
			To rename a category, just click it and modify its text.<br/>
		'); ?>
	</p>
</div>

<?php
	$this->css->load(array('categories.css', 50));
	$this->js->load('jquery.jeditable.mini.js', 'jquery.json-1.3.min.js', 'categories.js');
?>
