<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<?php 
	$this->doctype('XHTML1_TRANSITIONAL');
	$this->headTitle($this->conf->general->common_title);
	$this->headTitle()->setSeparator(' - ');
	echo $this->headTitle();
	echo $this->headMeta();
?>

<?php
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/global.css");
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/login.css");
	$this->headScript()
		->prependFile($this->baseUrl . '/public/js/functions.js')
		->prependScript($this->translateHash, 'text/javascript', array('charset' => 'UTF-8'))
		->prependFile($this->baseUrl . '/public/js/lib/jquery.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.corner.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.pngFix.pack.js', 'text/javascript')		
		->appendFile($this->baseUrl . '/public/js/global.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/login.js', 'text/javascript');
	
	echo $this->headLink();
	echo $this->headStyle();
?>

</head>
<body>
	<div id="wrapper">
		<div id="joobsbox-main">
			<?php echo $this->layout()->content;?>
			<div id="joobsbox-license">
				powered by <a href="http://www.joobsbox.com" rel="external" target="_blank">joobsbox</a> + <a href="http://www.joobs.ro" rel="external" target="_blank">joobs.ro</a> + <a href="http://framework.zend.com" rel="external" target="_blank">zend framework</a>
			</div>
		</div>
	</div>
	<?php echo $this->headScript(); ?>
</body>
</html>
