<?php $this->headTitle()->prepend($this->translate('Publish a job posting')); $this->headLink()->appendStylesheet($this->themeUrl . "/css/publishForm.css"); ?>
<div class="inner">
	<?php echo $this->translate('Publish a job'); ?>
</div>
<?php
if($this->addSuccess) {
	echo '<div class="message">' . $this->translate("The job has been saved. It now has to be accepted by a moderator in order to appear publicly on the site.") . '</div>';
} else if($this->editSuccess) {
	echo '<div class="message">' . $this->translate("The job has been modified and saved.") . '</div>';
} else {
	echo $this->form;
}
?>
