<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headTitle()->prepend($this->translate('Publish a job posting')); $this->headLink()->appendStylesheet($this->themeUrl . "/css/publishForm.css"); ?>
<div class="inner">
	<?php echo $this->translate('Publish a job'); ?>
</div>
<?php
if($this->addSuccess) {
	echo '<div class="message">' . $this->translate("The job has been saved. It now has to be accepted by a moderator in order to appear publicly on the site.") . '</div>';
} else if($this->editSuccess) {
	echo '<div class="message">' . $this->translate("The job has been modified and saved.") . '</div>';
} else {
	echo $this->form;
}

$this->asset->load("jquery");
$this->asset->load("jquery-ui");
$this->headScript()->appendFile($this->themeUrl . '/js/publish.js');
?>
