<ul class="postings">
	<?php foreach($this->pending as $a => $job): ?>
		<li <?php if($a%2):?>class="alternate"<?php endif;?>>
			<a href="<?php echo $this->baseUrl;?>/job/<?php echo $this->MakeLink($job['title']) . "-" . $job['id']; ?>.html"><?php echo $this->filter("job_title", $job['title']); ?></a>
			<span class="lighterSmall"> <?php echo $this->translate("at"); ?> </span>
			<?php echo $this->filter("job_company", $job['company']); ?>
			<span class="lighterSmall"> <?php echo $this->translate("in"); ?> </span>
			<?php echo $this->filter("job_location", $job['location']); ?>
		</li>
	<?php endforeach; ?>
</ul>

<div class="info">
	<a href="postings/"><?php echo $this->translate("Total postings:") . ' ' . count($this->postings); ?></a>
	<a href="postings/"><?php echo $this->translate("Pending postings:") . ' ' . count($this->pending); ?></a>
</div>
