<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php
    $this->headTitle()->prepend($this->translate("Dashboard"));
?>
<h1 class="dashboard-title"><?php echo $this->translate("Dashboard"); ?></h1>
<ul id="dashboard">
<?php
	foreach($this->dashboard as $pluginName => $pluginDashboardContent):
?>
		<li class="dashboard-item">
			<div class="dashboard-item-title"><?php echo $pluginDashboardContent['options']->main->{'title_' . $this->locale}; ?></div>
			<div class="dashboard-item-content">
				<?php
					echo $pluginDashboardContent['content'];
				?>
			</div>
		</li>
<?php
	endforeach;
?>
	<div class="clear">&nbsp;</div>
</ul>
