<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headScript()->appendFile($this->themeUrl . '/js/login.js'); ?>
<div>
	<?php 
		echo $this->form; 
		if(isset($this->loginError)) {
	?>
		<div class="error"><?php echo $this->loginError; ?></div>
	<?php
		}
	?>
</div>