<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<?php 
	$this->headTitle($this->conf->general->common_title);
	$this->headTitle()->setSeparator(' - ');
	echo $this->headTitle();
?>

<?php
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/global.css");
	$this->headScript()
		->prependFile($this->baseUrl . '/public/js/functions.js')
		->prependScript($this->translateHash, 'text/javascript', array('charset' => 'UTF-8'))
		->prependFile($this->baseUrl . '/public/js/lib/jquery.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.corner.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.pngFix.pack.js', 'text/javascript')		
		->appendFile($this->baseUrl . '/public/js/global.js', 'text/javascript');
	echo $this->headLink();
	echo $this->headStyle();
	echo $this->headScript(); 
?>
</head>
<body>
	<h1 class="site-title"><?php echo $this->headTitle(); ?></h1>
	<div id="wrapper">
		<div id="main">
			<div id="header"><a href="<?php echo $this->baseUrl; ?>"></a></div>
			<div id="tools">
				<div id="postJob">
					<a href="<?php echo $this->baseUrl . '/' . $this->TranslateUrl('publish'); ?>">
						<?php printf($this->translate("Post a job for %d days"), $this->conf->general->posting_ttl); ?>
					</a>
				</div>
				<div id="search">
					<form action="<?php echo $this->baseUrl . '/' . $this->TranslateUrl('search'); ?>" method="get">
						<div id="searchInputContainer"><input name="txtSearch" type="text" id="searchInput" value="<?php echo $this->translate("Search here"); ?>" /></div>
						<div id="searchButtonContainer"><input type="image" src="<?php echo $this->themeImages; ?>/search.jpg" /></div>
					</form>
				</div>
			</div>
			<?php echo $this->layout()->content;?>
			<div id="footer">
				powered by <a href="http://www.joobsbox.com" rel="external" target="_blank">joobsbox</a> + <a href="http://www.joobsb.ro" rel="external" target="_blank">joobs.ro</a> + <a href="http://framework.zend.com" rel="external" target="_blank">zend framework</a>
			</div>
		</div>
	</div>
</body>
</html>
