<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<?php 
	$this->doctype('XHTML1_TRANSITIONAL');
	$this->headTitle($this->conf->general->common_title);
	$this->headTitle()->setSeparator(' - ');
	echo $this->filter('head_html');
	echo $this->headTitle();
	echo $this->headMeta();
?>

<?php
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/global.css");
	$this->headScript()
		->prependFile($this->baseUrl . '/public/js/functions.js')
		->prependScript($this->translateHash, 'text/javascript', array('charset' => 'UTF-8'))
		->prependFile($this->baseUrl . '/public/js/lib/jquery.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.corner.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.pngFix.pack.js', 'text/javascript')		
		->appendFile($this->baseUrl . '/public/js/global.js', 'text/javascript');
	
	// Link the main RSS file
  $this->headLink()->appendAlternate($this->baseUrl . '/rss', 'application/rss+xml', $this->conf->general->common_title . ' RSS');
  
	echo $this->headLink();
	echo $this->headStyle();
?>

</head>
<body>
	<h1 class="site-title"><?php echo implode($this->headTitle()->getSeparator(), (array)$this->headTitle()->getContainer()); ?></h1>
	<div id="wrapper">
		<div id="joobsbox-main">
			<div id="joobsbox-header">
			  <h1><a href="<?php echo $this->baseUrl; ?>"><?php echo $this->conf->general->common_title; ?></a></h1>
			  <h2>This is the php demo of the most flexible open source job board application. <br/>Follow <a href="http://twitter.com/joobsbox">@joobsbox</a> to know when we launch next version. Check the <a href="<?php echo $this->baseUrl; ?>/admin">Administration</a></h2>
			</div>
			<div id="tools">
				<div id="postJob">
					<a class="button" href="<?php echo $this->baseUrl . '/' . $this->TranslateUrl('publish'); ?>">
						<?php printf($this->translate("Post a job for %d days"), $this->conf->general->posting_ttl); ?>
					</a>
				</div>
				<div id="search">
					<form action="<?php echo $this->baseUrl . '/' . $this->TranslateUrl('search'); ?>" method="get">
						<input name="txtSearch" type="text" id="searchInput" value="<?php echo $this->translate("Search here"); ?>" />
						<input class="button" type="submit" value="<?php echo $this->translate('Search'); ?>" />
					</form>
				</div>
			</div>
			<?php echo $this->layout()->content;?>
			<div id="joobsbox-footer">
				<?php printf($this->translate('Subscribe to the full <a href="%s">RSS Feed</a> and be notified when new jobs are posted.'), $this->baseUrl . '/rss'); ?>
			</div>
			<div id="joobsbox-license">
				powered by <a href="http://www.joobsbox.com" rel="external" target="_blank">joobsbox</a> + <a href="http://www.joobs.ro" rel="external" target="_blank">joobs.ro</a> + <a href="http://framework.zend.com" rel="external" target="_blank">zend framework</a>
			</div>
		</div>
	</div>
	<?php echo $this->headScript(); ?>
	<script type="text/javascript">
    var uservoiceJsHost = ("https:" == document.location.protocol) ? "https://uservoice.com" : "http://cdn.uservoice.com";
    document.write(unescape("%3Cscript src='" + uservoiceJsHost + "/javascripts/widgets/tab.js' type='text/javascript'%3E%3C/script%3E"))
  </script>
  <script type="text/javascript">
  UserVoice.Tab.show({ 
    key: 'joobsbox',
    host: 'joobsbox.uservoice.com', 
    forum: 'general', 
    alignment: 'left',
    background_color:'#0069BF', 
    text_color: 'white',
    hover_color: '#0881E4',
    lang: 'en'
  })
  </script>
</body>
</html>
