<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<?php 
	$this->headTitle($this->conf->general->common_title);
	$this->headTitle()->setSeparator(' - ');
	echo $this->headTitle();
?>

<?php
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/global.css");
	$this->headLink()->appendStylesheet($this->themeUrl . "/css/install.css");
	$this->headScript()
		->prependFile($this->baseUrl . '/public/js/functions.js')
		->prependScript($this->translateHash, 'text/javascript', array('charset' => 'UTF-8'))
		->prependFile($this->baseUrl . '/public/js/lib/jquery.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.corner.js', 'text/javascript')
		->appendFile($this->baseUrl . '/public/js/lib/jquery.pngFix.pack.js', 'text/javascript')		
		->appendFile($this->baseUrl . '/public/js/global.js', 'text/javascript');
	echo $this->headLink();
	echo $this->headStyle();
	echo $this->headScript(); 
?>
</head>
<body>
	<div id="wrapper">
		<div id="joobsbox-main">
			<div id="joobsbox-header"><?php echo $this->translate("Installation"); ?></div>
			<?php echo $this->layout()->content;?>
			<div id="footer">
				<a href="http://framework.zend.com/">
					<img src="<?php echo $this->themeImages; ?>/PoweredBy_ZF_4LightBG.png" border="0">
				</a>
				<!--
				<a href="http://www.joobs.ro">
					<img src="<?php echo $this->themeImages; ?>/powered-by-joobs.ro.gif" alt="POWERED BY Joobs.ro" />
				</a>
				-->
			</div>
		</div>
	</div>
</body>
</html>
