<?php
/**
 * @package Joobsbox_Themes
 * @category Joobsbox
 * @author Valentin Bora <contact@valentinbora.com>
 * @version 1.0
 * @copyright  Copyright (c) 2009 Joobsbox. (http://www.joobsbox.com)
 * @license	   http://www.joobsbox.com/joobsbox-php-license
 */
?>
<?php $this->headTitle($this->translate("Jobs at") . ' ' . $this->searchedCompany); ?>
	<div class="list">
		<div class="inner">
			<a href="#">
				<?php echo $this->translate("Jobs at") . ' ' . $this->searchedCompany; ?>
			</a>
		</div>
			<ul>
				<?php foreach($this->jobs as $a => $job): ?>
				<li <?php if($a%2):?>class="alternate"<?php endif;?>>
					<a href="<?php echo $this->baseUrl;?>/job/<?php echo $this->MakeLink($job['Title']) . "-" . $job['ID']; ?>.html"><?php echo $this->filter("job_title", $job['Title']); ?></a>
					<span class="lighterSmall"> <?php echo $this->translate("at"); ?> </span>
					<?php echo $this->filter("job_company", $job['Company']); ?>
					<span class="lighterSmall"> <?php echo $this->translate("in"); ?> </span>
					<?php echo $this->filter("job_location", $job['Location']); ?>
				</li>
				<?php endforeach; ?>
			</ul>
	</div>