<h1 class="dashboard-title"><?php echo $this->translate("Users") . ' - ' . $this->translate("Edit your profile"); ?></h1>
<div class="joobsbox-plugin-content">
  <span class="info"><?php echo $this->translate("To change any of this data you must input your old password."); ?></span>
  <?php echo $this->form; ?>
</div>
<?php
	$this->headLink()->appendStylesheet($this->themePath . 'css/users.css');
?>
