<div id="joobsbox-footer">
	<?php printf($this->translate('Subscribe to the full <a href="%s">RSS Feed</a> and be notified when new jobs are posted.'), $this->baseUrl . '/rss'); ?>
</div>
<div id="joobsbox-license">
	<?php echo $this->translate("powered by"); ?> <a href="http://www.joobsbox.com" rel="external" target="_blank">joobsbox</a> + <a href="http://www.joobs.ro" rel="external" target="_blank">joobs.ro</a> + <a href="http://framework.zend.com" rel="external" target="_blank">zend framework</a>
</div>
</div>