<h1 class="site-title"><a href="<?php echo $this->baseUrl; ?>"><?php echo $this->conf->general->common_title; ?></a></h1>
<div id="joobsbox-header">
  <?php if($this->conf->general->demo): ?>
  <h2>This is the php demo of the most flexible open source job board application. <br/>Follow <a href="http://twitter.com/joobsbox">@joobsbox</a> to know when we launch next version. Check the <a href="<?php echo $this->baseUrl; ?>/admin/">Administration</a></h2>
  <div class="temporary" style="margin-left: 10px; font-size: 12px; color: #E38C09;">Note: this theme is a work in progress</div>
  <div class="temporary" style="margin-left: 10px; font-size: 12px; color: #E38C09;">Disclaimer: The jobs listed here have demonstration purposes only</div>
  <?php endif; ?>
</div>
<div id="tools">
	<div id="postJob">
		<a class="button" id="publishBtn" href="<?php echo $this->baseUrl . '/' . $this->TranslateUrl('publish'); ?>">
			<?php printf($this->translate("Post a job for %d days"), $this->conf->general->posting_ttl); ?>
		</a>
	</div>
	<div id="search">
		<form action="<?php echo $this->baseUrl . '/' . $this->TranslateUrl('search'); ?>" method="get">
			<input name="txtSearch" type="text" id="searchInput" value="<?php echo $this->translate("Search here"); ?>" />
			<input class="button" id="searchBtn" type="submit" value="<?php echo $this->translate('Search'); ?>" />
		</form>
	</div>
</div>