-- phpMyAdmin SQL Dump
-- version 3.1.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 13, 2009 at 10:42 PM
-- Server version: 5.1.30
-- PHP Version: 5.2.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `jobboard`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `OrderIndex` tinyint(4) NOT NULL,
  `Parent` tinyint(4) NOT NULL,
  `lft` int(11) NOT NULL,
  `rgt` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `OrderIndex` (`OrderIndex`),
  KEY `Parent` (`Parent`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC AUTO_INCREMENT=6 ;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`ID`, `Name`, `OrderIndex`, `Parent`, `lft`, `rgt`) VALUES
(2, 'Programare', 1, 0, 0, 0),
(3, 'Design', 2, 0, 0, 0),
(4, 'Management', 3, 0, 0, 0),
(5, 'Administrare', 4, 0, 0, 0),
(1, 'Uncategorized', 100, 0, 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `jobs`
--

DROP TABLE IF EXISTS `jobs`;
CREATE TABLE IF NOT EXISTS `jobs` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CategoryID` int(11) NOT NULL DEFAULT '0',
  `Title` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `Description` varchar(4000) COLLATE utf8_unicode_ci NOT NULL,
  `ToApply` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `Company` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  `Location` varchar(120) CHARACTER SET utf8 COLLATE utf8_esperanto_ci NOT NULL,
  `Public` tinyint(1) NOT NULL DEFAULT '0',
  `ExpirationDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ChangedBy` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `ChangedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `CodeStamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `CategoryID` (`CategoryID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC AUTO_INCREMENT=110 ;

--
-- Dumping data for table `jobs`
--

INSERT INTO `jobs` (`ID`, `CategoryID`, `Title`, `Description`, `ToApply`, `Company`, `Location`, `Public`, `ExpirationDate`, `ChangedBy`, `ChangedDate`, `STATUS`, `CodeStamp`) VALUES
(45, 1, 'Junior C# ASP.Net developer', 'NetMatch as employer:\r\n- NetMatch is the European market leader in Tourism Internet Software Solutions. We assists travel companies in selling their products online. \r\n- NetMatch provides essential (dedicated side-by-side) training and we encourage candidates in getting an MCSD certificate.\r\n\r\n\r\nCandidate profile: \r\n* You have a IT software related University diploma or comparable;\r\n* You have knowledge of C# and ASP.NET;\r\n* You have knowledge of object orientated programming and designing with UML;\r\n* You have knowledge of XML applications like XHTML, XSIT, XPATH and XML scheme.\r\n* You have a strong personality and can handle stress. You are accurate in work in structure, and you react quickly and flexible to ad-hoc situations. \r\n', 'Trimite CV la email la :jobs@netmatch.ro ', 'NetMatch SRL', 'Cluj-Napoca ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(46, 1, 'NET developers & Senior .NET developers ', 'IDEAL CANDIDATE:\r\n\r\nProfile:\r\n- You have an IT software related University diploma or you are a student of a related University.\r\n- You have experience working with the Microsoft .NET Framework;\r\n- You have knowledge of object orientated analysis and designing with UML;\r\n- You have worked with XML languages like XHTML, XSLT, XPATH and XML schema.\r\n- A relevant Microsoft certificate (MCSD or MCAD) is a plus.\r\n\r\nJOB RESPONSIBILITIES / BENEFITS:\r\n\r\nYou are responsible for the release of the newest versions of websites and services of travel organizations internationally. You translate a wish into a solution. You seek and discover new techniques. You document designs and code carefully with UML. Grow with the company and make a real impact in shaping both your and the companyâ€™s future.\r\n\r\nYou are responsible for quality, without losing track of development speed. You coach your colleagues on the newest internet technology that you know by heart and you happily share your knowledge with others.\r\n\r\nNetMatch as employer:\r\n- Offers candidates a great chance to develop skills, working with a team of highly motivated and talented Romanian and Dutch software developers using the latest technologies such as .NET, XML, XSLT, etc.\r\n- NetMatch provides essential (dedicated side-by-side) training and we encourage candidates in getting an MCSD certificate.\r\n- Offers an exciting opportunity to work abroad (temporarily or for a longer time) in the Netherlands, so travel is a possibility.\r\n- Competitive salaries and benefits (500 - 1500 Euro)\r\n\r\nCOMPANY OR JOB DESCRIPTION:\r\n\r\nNetMatch assists travel companies in selling their products online. For this NetMatch has developed a .NET application named TourWeb. Our biggest client group currently consists of tour operators that sell their products online with TourWeb. http://www.netmatch.nl/downloads/tourweb2006EN.pdf\r\n\r\nNetMatch is the European market leader in Tourism Internet Software Solutions.\r\n\r\nwww.netmatch.ro\r\nwww.netmatch.nl \r\n', 'Trimite CV la email: jobs@netmatch.ro ', 'NetMatch SRL', 'Cluj-Napoca ', 0, '2007-12-15 12:00:00', '', '2009-04-02 23:43:09', 0, '0000-00-00 00:00:00'),
(47, 1, 'C++ Programmers', 'Top software company, with over 1,200 customers in 120 countries, among them 49 of the world''s top 50 banks, is expanding its treasury & capital markets branch in Bucharest. Here we are creating one of the most important development centers of the company, with top specialists working on sophisticated products. \r\n\r\nAt the very heart of the financial software industry, you will be able to achieve exponential career growth, have access to professional training programs and be highly rewarded for your efforts. \r\n\r\nWe believe that everything starts with talent. \r\n\r\nTo learn more about Misys, please log on to www.misys.com \r\n\r\nRequirements: \r\n- University degree: Computer Science, Mathematics, Business IT (ASE) \r\n- Very good knowledge of C, C++ and/or C# \r\n- Knowledge of .NET, Java, Perl, RDBMS appreciated \r\n- Real-time and Distributed Processing appreciated \r\n- Good English knowledge \r\n- Interest in finance \r\n- Commitment, stability, responsibility \r\n- Ability to work independently as well as being a team player \r\n- Excellent verbal and written communication skills \r\n- Time management skills and the ability to work under tight time constraints \r\n- Ability to multi-task between multiple activities \r\n\r\nResponsibilities: \r\n- Develop new financial applications and improve existing modules \r\n- Perform unit testing \r\n- Write technical specifications \r\n- Provide maintenance for existing projects \r\n- Investigate technical and functional defects and propose adequate solutions \r\n- Provide product-related and domain specific consultancy \r\n- Write documentation \r\n- Learn new IT and finance skills, as required \r\n- Travel and direct interaction with client may be required \r\n\r\nBenefits: \r\n- Motivating salary and bonuses, according to results \r\n- Opportunity to develop software projects in a professional environment \r\n- Access to high-end technology \r\n\r\n\r\n', 'If you''re interested in becoming a part of our team of professionals, please send your CVs at mariana.pascu@misys.com , and we''ll be happy to schedule a meeting. ', 'MISYS International Financial Systems', 'Bucuresti ', 0, '2007-12-15 12:00:00', '', '2009-04-02 23:43:09', 0, '0000-00-00 00:00:00'),
(48, 1, 'Aplication Manager', 'Descrierea jobului: \r\n- Asigura analiza, proiectarea, programarea si implementarea de solutii software; \r\n- Asigura mentenanta si suport pentru sistemul informatic; \r\n- Asigura dezvoltarea si mentenanta programelor software integrate cu sistemul informatic. \r\n\r\nCerinte: \r\n- Studii superioare cu specializare in informatica; \r\n- Cunostinte solide MS SQL - administrare, proiectare, programare; \r\n- Capacitate de a asimila rapid noi cunostinte; \r\n- Spirit de echipa. \r\n\r\nConstituie avantaj: \r\n- Cunosterea unui limbaj de programare ( preferabil promovat de Microsoft ); \r\n- Cunostinte ERP iSCALA; \r\n- Experienta minim 1 an intr-o pozitie similara. \r\n', 'trimite CV la e-mail: hr@rhs.ro ', 'RHS COMPANY', 'Bucuresti ', 0, '2007-12-15 12:00:00', '', '2009-04-02 23:43:09', 0, '0000-00-00 00:00:00'),
(49, 1, 'Programator Flash + PHP', 'CANDIDATUL IDEAL: \r\n\r\nProgramator cu inclinatie artistica (sa inteleaga si sa dezvolte ideile directorului de creatie), nivel mediu ActionScripting, cu dorinta continua de dezvoltare, inventiv. \r\n\r\nRESPONSABILITATI \r\n\r\n- dezvoltarea modulelor Flash pentru site-uri (headere, micro-module de calcul, etc) sau chiar a site-urilor integral Flash) \r\n- dezvoltarea bannerelor rich-media, optimizare, integrare sunet si video \r\n- dezvoltarea mini-jocurilor Flash \r\n- transpunerea dinamica a viziunii directorului de creatie \r\n\r\nCERINTE: \r\n\r\n- Integrare grafica in mediul Flash (site web, bannere, aplicatii stand-alone pentru CD) \r\n- Integrare Flash cu XML/PHP/MySQL \r\n\r\nNIVEL: mediu. \r\n\r\nOFERTA (BONUSURI, BENEFICII): \r\n\r\nSe acorda pachet salarial motivant (salariu de baza + bonus progresiv) in functie de performanta. Proiecte interesante cu clienti la fel de interesanti (vezi portfolio-ul partial al agentiei). Integrarea intr-o echipa cu experienta in dezvoltarea de proiecte atit on-line cat si off-line. \r\n\r\nDESCRIEREA COMPANIEI: \r\n\r\nThe Adgency este o agentie de creatie si design interactiv, consultanta de brand si comunicare integrala, fondata Ã®n 2004, cu capital exclusiv romanesc. Din 2006 The Adgency este certificata ISO 9001. \r\n', 'Trimite CV la office@theadgency.ro ', 'The Adgency', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(50, 1, 'Java Developer', 'Coena is a product development company that specializes in developing state-of-the-art supply chain products.\r\n\r\nWe use techniques from distributed technologies, artificial intelligence, model-driven architecture, and object-oriented technology.\r\n\r\nWe are looking for motivated and quality-driven software professionals to start work on our products in our office in Romania (Cluj-Napoca).\r\n\r\nEligible candidates must meet the following requirements:\r\n- Bachelor''s degree in Computer Science from a recognized University.\r\n- At least 2 years working experience.\r\n- Applicable candidates must demonstrate strong commitment to learning and delivering high quality code.\r\n- Thorough and demonstrable knowledge of Object-Oriented Analysis and Design.\r\n- AJAX-based frameworks, J2EE/Distributed Enterprise Technologies, Domain-driven development.\r\n- Should be fluent in English and have good communication skills.\r\n\r\nWe offer competitive salaries, and an excellent career growth path in leading technologies. \r\n', 'Eligible candidates must provide their Curriculum Vitae (CV) in English to recruitment@coena.ro . Selected candidates will be contacted for a face-to-face interview in Cluj-Napoca. ', 'Coena SRL', 'Cluj-Napoca ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(51, 1, 'Front-End Web Developer', 'F5 Solutions cauta un Front-End Web Developer care sa raspunda afirmativ la cel putin 5 din urmatoarele 8 intrebari:\r\n\r\n1) Poti face o comparatie intre cel putin 2 framework-uri JavaScript ?\r\n2) Codul XHTML scris de tine este corect din punct de vedere semantic ?\r\n3) Preferi un editor de tip TEXT (cu sintax-highlighting) in detrimentul unui editor de tip WYSIWYG ?\r\n4) Cunosti cel putin o solutie pentru realizarea unui transfer asincron de date cross-domain ?\r\n5) Obisnuiesti sa validezi codul XHTML / CSS conform standardelor W3C ?\r\n6) "Cross-Browser", "fiabilitate" si "scalabilitate" se numara printre caracteristicile definitorii ale proiectelor tale ?\r\n7) Esti familiar cu cel putin 4 dintre urmatorii termeni: "hasLayout", "mostenire", "DOM", "elemente multi-class", "polimorfism" ?\r\n8) Ai folosit pana acum o tehnologie text-based de serializare / transmitere a datelor in afara de XML ?\r\n\r\nCunostintele si conditiile obligatorii sunt urmatoarele:\r\n\r\n- XHTML, CSS;\r\n- XML, XSLT, JSON;\r\n- JavaScript (OOP, minim 4 luni experienta in utilizarea unui framework);\r\n- Un portofoliu care sa cuprinda cel putin 3 proiecte / experimente / aplicatii relevante;\r\n- Seriozitate, responsabilitate, etica profesionala;\r\n- Simtul umorului (nu glumim).\r\n\r\nEsti avantajat daca:\r\n\r\n- Ai experienta in utilizarea Smarty;\r\n- Ai experienta in utilizarea Fireworks si/sau Photoshop (slicing / export);\r\n- Esti familiar cu modul de functionare al tehnologiilor server-side (cel putin la nivel de concept);\r\n- Te implici, esti activ si stii sa-ti exprimi / argumentezi propriile idei si convingeri;\r\n- Esti intr-un proces continuu de autodepasire.\r\n\r\nBeneficii:\r\n\r\n- Proiecte complexe si incitante;\r\n- Pachet salarial si bonusuri atractive;\r\n- Programul (flexibil) incepe undeva in jurul orei 11:00 (somn++, trafic--);\r\n- Atmosfera placuta si degajata;\r\n- Sansa de a te "razbuna" zilnic pe colegii utilizand "armele din dotare" (X-BOX / PC gaming sessions)\r\n\r\nProgram:\r\n\r\nFull-Time \r\n', 'Trimite CV-ul tau la jobs [at] f5solutions [dot] ro ', 'F5 Solutions', 'Bucuresti', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(52, 1, '  .net web developer ', 'We are looking for candidates that have:\r\n- Knowledge of .NET Technologies, OOP, SQL Server, Web based communications\r\n- Knowledge of HTML, XHTML and CSS is definitely a plus.\r\n- Good English Skills â€“ spoken, written and comprehension (good communication skills are essential for understanding our clients needs )\r\n- Solid work ethic and excellent time management skills\r\n- Positive attitude and self-motivated\r\n- Flexibility in thinking.\r\n\r\n\r\nDaily activity will cover:\r\n- Designing the system architecture together with the software architect\r\n- Working as a team member in development of web and/or desktop applications\r\n- Consulting with the rest of the team and provide input on improving internal processes\r\n\r\n\r\nBenefits:\r\n- Interesting work on international projects\r\n- Friendly and professional work setting\r\n- Flexible schedule â€“ students are allowed to go to necessarily classes, as long as lost time is covered and the work is finished until the deadline.\r\n- Reevaluation of the work at every 3-4 mounts. Each time the salary can be increased if the work done so far is excellent.\r\n- Great opportunity to become Team Leader.\r\n', 'Trimite CV la email jobs@evoluxis.com ', 'Evoluxis', 'Cluj Napoca', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(53, 1, '.net desktop developer', 'We are looking for candidates that have:\r\n- Knowledge of .NET Technologies, OOP, SQL Server\r\n- Knowledge of HTML, XHTML and CSS is a plus.\r\n- Good English Skills â€“ spoken, written and comprehension (good communication skills are essential for understanding our clients needs )\r\n- Solid work ethic and excellent time management skills\r\n- Positive attitude and self-motivated\r\n- Flexibility in thinking.\r\n\r\nDaily activity will cover:\r\n- Designing the system architecture together with the software architect\r\n- Working as a team member in development of web and/or desktop applications\r\n- Consulting with the rest of the team and provide input on improving internal processes\r\n\r\n\r\nBenefits:\r\n- Interesting work on international projects\r\n- Friendly and professional work setting\r\n- Flexible schedule â€“ students are allowed to go to necessarily classes, as long as lost time is covered and the work is finished until the deadline.\r\n- Reevaluation of the work at every 3-4 mounts. Each time the salary can be increased if the work done so far is excellent.\r\n- Great opportunity to become Team Leader.\r\n\r\n', 'Trimite CV la email jobs@evoluxis.com ', 'Evoluxis', 'Cluj Napoca', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(54, 1, 'Software Developer', 'Good knowledge in C/C++ and Visual Basic.\r\n\r\n- Develop/maintain plug-ins for various text/XML editor applications (e.g. MS Word, Adobe InDesign, oXygen)\r\n- New functionalities development accordingly with technical specification provided\r\n\r\nRequirements:\r\n- Good skills in C/C++, Visual Basic\r\n- Experience with OOP\r\n- Be willing to learn new APIs\r\n- Good command of English language\r\n\r\nWould be a plus:\r\n- COM/ATL\r\n- C#, .NET\r\n- VBScript, JScript\r\n\r\nWe offer:\r\n- International team \r\n- Multifaceted work \r\n- Opportunity to contribute your ideas and creativity to innovative software products \r\n- Growing company with diverse opportunities for further development \r\n- Young and friendly team \r\n', 'If you are qualified, please send your application, salary expectations and possible starting date to hr@acrolinx.com . Please include any attachments as PDF files. ', 'acrolinx GmbH', 'Bucuresti/Iasi ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(55, 1, 'Software Devlopers & Telecom Engineers', '1) User Interface Developers\r\n\r\nRequired skills:\r\n- Linux basics\r\n- C & standard library\r\n- Basic GNU development tools (gcc, make, autotools, etc.)\r\n- GTK+\r\n- GUI builders (Glade, Gazpacho, libglade, GTKbuilder)\r\n\r\nExtra skills:\r\n- GObject & ability to create custom widgets\r\n- Theming with gtkrc\r\n- OpenGL (ES version), EDJE and Cairo. Also knowing clutter would be beneficial\r\n\r\n2) Application Developers (Linux/Windows)\r\n\r\nRequired skills:\r\n- Linux basics\r\n- C & standard library\r\n- Basic GNU development tools (gcc, make, autotools, etc.)\r\n- Experience of Linux programming API (threads, IPC, I/O, sockets)\r\n- Glib (data structures, basic types)\r\n\r\nExtra skills:\r\n- Libtool & building shared libraries\r\n- Knowledge of GNOME/freedesktop.org architecture components\r\n- e.g. D-BUS, gconf, GnomeVFS\r\n\r\n3) Telecom/SS7/GSM Engineers\r\n\r\nMandatory:\r\n- Availability to intensive travel abroad\r\n- Work experience in telecom domain\r\n- Experience with Unix (Solaris of HP-UX) server-side system, administration tools and shell scripting\r\n- Knowledge of Oracle\r\n- Excellent verbal and written communication, problem solving and analytical skill\r\n\r\nWill be an advantage:\r\n- Hands-on experience in developing call-processing and messaging applications in GSM/GPRS\r\n- Thorough knowledge of MAP, ISUP, IN, CAMEL, Network Elements such as HLR, VLR, SMSC, GMSC\r\n\r\n4) Embedded Software Developers\r\n\r\n- 3+ years C/C++ languages experience\r\n- 1+ year experience with embedded systems, on-chip debuggers\r\n- Knowledge of OS fundamentals, RTOS\r\n- Knowledge of device drivers, BSP, HW architectures\r\n- Software configuration management (CVS, Clearcase)\r\n\r\nWill be an advantage:\r\n- Experience with ARM processors\r\n- Experience in board design/testing \r\n', 'Feel free to send your resume at: office@altdev.ro ', 'AltDev', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(56, 1, 'Programator ASP.NET si SQL Server', 'CANDIDATUL IDEAL:\r\n\r\n- cunostinte foarte bune baze de date relationale (MS SQL Server)\r\n- cunostinte foarte bune ASP.NET, XML, JavaScript\r\n- minim 2 ani experienta\r\n- Abilitati de comunicare\r\n\r\n\r\nRESPONSABILITATI / BENEFICII:\r\n\r\nRolul principal pentru acest post este de a programa in ASP.Net si SQL Server 2000/2005, de a identifica solutii de optimizare si de scalare pentru o serie de aplicatii complexe, de mari dimensiuni.\r\nVor fi considerati pentru interviu doar candidatii cu experienta demonstrabila in .Net. Sunt de asemenea necesare cunostinte solide de SQL.\r\nNivelul minim de educatie este licenta in informatica (Matematica, Automatica, Cibernetica). Candidatii pot fi si studenti in ani terminali la facultatile amintite. \r\n\r\n', 'AplicÄƒ on-line la www.boom.ro/jobs ', 'NetBridge Investments', 'BucureÅŸti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(57, 1, 'Junior C++ Software Developer', 'Graitec Roumanie este dezvoltator direct de software pentru proiectarea asistatÄƒ de calculator Ã®n domeniul construcÅ£iilor.\r\nPentru sucursala din BucureÅŸti, suntem Ã®n cÄƒutare de candidaÅ£i dispuÅŸi sÄƒ lucreze full-time Ã®ntr-un mediu competitiv.\r\n\r\nDescrierea postului:\r\nâ€¢ Dezvoltarea de aplicaÅ£ii Ã®n Visual C++ \r\nâ€¢ Testarea minimalÄƒ a componentelor dezvoltate \r\nâ€¢ MentenanÅ£a componentelor dezvoltate \r\nâ€¢ Investigarea erorilor ÅŸi propunerea de soluÅ£ii adecvate \r\nâ€¢ ConsultanÅ£Äƒ pentru proiectele dezvoltate.\r\n\r\nCerinÅ£e\r\nDispunÃ¢nd de cunoÅŸtinÅ£e de bazÄƒ de: \r\nâ€¢ Visual C++ \r\nâ€¢ Limba englezÄƒ\r\n\r\nDe asemenea, cunoaÅŸterea oricÄƒreia din tehnologiile de mai jos reprezintÄƒ avantaje: \r\nâ€¢ MFC \r\nâ€¢ Windows API / SDK \r\nâ€¢ ObjectARX \r\nâ€¢ ActiveX \r\nâ€¢ COM / ATL. \r\nâ€¢ OLE \r\nâ€¢ ADO / DAO \r\nâ€¢ ODBC, SQL\r\nâ€¢ Limba francezÄƒ ÅŸi / sau germanÄƒ \r\n', 'Trimite CV la email jobs@graitec.ro ', 'Graitec Roumanie SRL', 'Bucuresti', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(58, 1, 'C++ Software Developer', 'Graitec Roumanie este dezvoltator direct de software pentru proiectarea asistatÄƒ de calculator Ã®n domeniul construcÅ£iilor.\r\nPentru sucursala din BucureÅŸti, suntem Ã®n cÄƒutare de candidaÅ£i dispuÅŸi sÄƒ lucreze full-time Ã®ntr-un mediu competitiv.\r\n\r\nDescrierea postului:\r\nâ€¢ Dezvoltarea de aplicaÅ£ii Ã®n Visual C++ \r\nâ€¢ Testarea minimalÄƒ a componentelor dezvoltate \r\nâ€¢ MentenanÅ£a componentelor dezvoltate \r\nâ€¢ Investigarea erorilor ÅŸi propunerea de soluÅ£ii adecvate \r\nâ€¢ ConsultanÅ£Äƒ pentru proiectele dezvoltate.\r\n\r\nCerinÅ£e\r\nDispunÃ¢nd de cunoÅŸtinÅ£e serioase de:\r\nâ€¢ Visual C++\r\nâ€¢ MFC\r\nâ€¢ Windows API / SDK\r\nâ€¢ Limba englezÄƒ\r\n\r\nDe asemenea, cunoaÅŸterea oricÄƒreia din tehnologiile de mai jos reprezintÄƒ avantaje: \r\nâ€¢ ObjectARX \r\nâ€¢ ActiveX \r\nâ€¢ COM / ATL. \r\nâ€¢ OLE \r\nâ€¢ ADO / DAO \r\nâ€¢ ODBC, SQL\r\nâ€¢ Limba francezÄƒ ÅŸi / sau germanÄƒ \r\n', 'Trimite CV la email jobs@graitec.ro ', 'Graitec Roumanie SRL', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(59, 1, 'PHP, MySQL programmer', 'eLink Telecom strongly believes that people are its most important resource. We value the quality and training of our staff because this is what defines our firmâ€™s performances. The quality growth, techincally speacking, is an aspect that we support and endorse.\r\n\r\nAt this moment, our firm has the following available positions:\r\n-PHP, MySQL programmer. \r\n', 'jobs@elinktelecom.ro ', 'ELink Telecom s.r.l', 'Bucuresti', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(60, 1, 'Consultant Vanzari', 'Gant & Sterling Consulting cauta pentru clientul sau, companie cunoscuta din domeniul IT&C \r\n\r\nConsultant Vanzari \r\n\r\nResponsabilitati: \r\nâ€¢ identifica proiecte/potentiali clienti pentru solutii de tehnica de calcul, sisteme integrate, securitate pentru sisteme informatice intr-un segment de piata alocat (banking-finance, telco-utilities, administratie centrala sau locala etc.) \r\nâ€¢ dezvolta strategia de abordare a fiecarui proiect \r\nâ€¢ initiaza, monitorizeaza, finalizeaza procesul de vanzare \r\nâ€¢ face account-management intensiv si profesional \r\n\r\n\r\nProfilul candidatului: \r\nâ€¢ experienta relevanta in vanzari â€“ minim 2 ani (ex.: sisteme industriale, utilaje, aparatura medicala, flote auto, servicii de date, asigurari, etc.) \r\nâ€¢ capacitate de intelegere a sistemelor IT (ca functionalitati de business, nu tehnic) \r\nâ€¢ disponibilitate si dorinta de a lucra in vanzari \r\nâ€¢ usurinta in comunicarea cu diferite personalitati, de la orice nivel ierarhic \r\nâ€¢ comunicare empatica, bun ascultator, extrovertit \r\nâ€¢ arie de acoperire culturala larga \r\nâ€¢ background tehnic/ economic/ matematica-informatica (de preferat) \r\nâ€¢ spirit de echipa, fara complexe sau timiditati \r\nâ€¢ cunoasterea limbii engleze la nivel bun \r\nSe ofera salariu fix plus bonus (comision), mediu de lucru dinamic, instruire de specialitate, posibilitate de dezvoltare profesionala. \r\n\r\n', 'Trimite CV la hr@gant.ro ', 'Gant & Sterling Consulting', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(61, 1, 'Client Service', 'CANDIDATUL IDEAL: \r\n\r\nPersoana comunicativa, sociabila, ordonata, placuta, de preferinta cu activitate anterioara in companii de web/it/publicitate, cu dorinta continua de dezvoltare, insistenta si inventiva. \r\n\r\nRESPONSABILITATI \r\n\r\n- coordonare comunicare interna (in agentie, de la client) si externa (agentie catre client) \r\n- gestionare conversatii (discutii/intalniri la client, memo, desfasurarea/evolutia proiectului, informarea clientului, informarea echipei din agentie) \r\n- research client (cine este, care au fost colaborarile sale anterioare si actuale cu agentii similare, ce isi doreste, ce si-ar mai putea dori in functie de evenimentele si mediile in care acesta este implicat) \r\n- prospectare / ofertarea serviciilor agentiei \r\n\r\nCERINTE: \r\n\r\n- bun organizator ("control freak") \r\n- experienta si deschidere catre comunicare (verbala, la telefon, in scris) \r\n- cunostinte specifice operarii pe calculator (Office) \r\n- avantaje: cunostinte generale web/it, si experienta anterioara in pozitii similare \r\n\r\nNIVEL: mediu. \r\n\r\nOFERTA (BONUSURI, BENEFICII): \r\n\r\nSe acorda pachet salarial motivant (salariu de baza + bonus progresiv) in functie de performanta. Proiecte interesante cu clienti la fel de interesanti (vezi portfolio-ul partial al agentiei). Integrarea intr-o echipa cu experienta in dezvoltarea de proiecte atit on-line cat si off-line. \r\n\r\nDESCRIEREA COMPANIEI: \r\nThe Adgency este o agentie de creatie si design interactiv, consultanta de brand si comunicare integrala, fondata Ã®n 2004, cu capital exclusiv romanesc. Din 2006 The Adgency este certificata ISO 9001.', 'Trimite CV la e-mail: office@theadgency.ro ', 'The Adgency', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(62, 1, 'Documentation Writer', 'Graitec Roumanie este dezvoltator direct de software pentru proiectarea asistatÄƒ de calculator Ã®n domeniul construcÅ£iilor.\r\nPentru sucursala din BucureÅŸti, suntem Ã®n cÄƒutare de candidaÅ£i dispuÅŸi sÄƒ lucreze full-time Ã®ntr-un mediu competitiv.\r\n\r\nDescrierea postului:\r\nDocumentation writer dispus sÄƒ Ã®nveÅ£e ÅŸi sÄƒ lucreze full-time Ã®ntr-un mediu competitiv, responsabil cu:\r\nâ€¢ Scrierea documentaÅ£iei aferente pachetelor oftware produse Ã®n cadrul firmei (fiÅŸiere de help, manuale de utilizare, documente "what''s new", etc) \r\nâ€¢ Asigurarea traducerii documentaÅ£iei (imagini ÅŸi text) cu ajutorul traducÄƒtorilor specializaÅ£i.\r\n\r\nCerinÅ£e:\r\nDispunÃ¢nd de cunoÅŸtinÅ£e serioase de: \r\nâ€¢ Office\r\nâ€¢ Limba englezÄƒ\r\nâ€¢ Software pentru graficÄƒ (Photoshop, PaintshopPro, Corel, etc)\r\n\r\nDe asemenea, urmÄƒtoarele reprezintÄƒ avantaje:\r\nâ€¢ CunoÅŸtinÅ£e de germanÄƒ ÅŸi / sau francezÄƒ\r\nâ€¢ ExperienÅ£Äƒ Ã®n construirea paginilor de help: Help Workshop, HTML, RoboHelp, Flash \r\nâ€¢ ExperienÅ£Äƒ Ã®n utilizarea pachetelor software de traducere automatÄƒ (TRADOS) \r\n', 'Trimite CV la email jobs@graitec.ro ', 'Graitec Roumanie SRL', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(63, 1, 'Database Manager ', 'Working as part of a highly experienced international data reporting team, you will be involved in: \r\n\r\n-Actively communicating with Project Managers, Knowledge Managers, Sales managers and other teams from our international office\r\n-Running queries on databases to select specific target groups\r\n-Using job-related software for performing database counts to assess feasibility of future projects\r\n-Ensuring top-quality of delivered data\r\n-Suggesting improvements to the databasesâ€™ content\r\n-Other database and technical tasks as necessary\r\n\r\n\r\nCerinte:\r\n\r\nWe require dedicated team members with varying degrees of experience. Ideally, you posses:\r\n\r\n- some knowledge in SQL\r\n- good knowledge in Ms Office, boolean logic and English\r\n\r\nImportant:\r\n\r\n- University training (preferably in science, technology or economic field) or experience with databases \r\n- Highly organized, precise, analytical, reliable\r\n- Excellent communication skills and team spirit\r\n- Ability to work well under time pressure\r\n\r\n\r\nOferta (bonusuri, beneficii):\r\n\r\n\r\nWe are offering the following benefits:\r\n\r\n- Attractive salaries \r\n- Holiday and performance bonuses, salary overdraft, meal tickets\r\n- Great opportunities for career development from entry level to senior positions\r\n- Intensive training opportunities in Timisoara and Munich (SQL, Project Management, etc)\r\n- Top office facilities, friendly environment and sports program', 'You can apply at jobs@ciao-ro.com ', 'Ciao Romania', 'Timisoara ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(64, 1, 'Test Case Developer', 'Responsabilitati:\r\n- dezvolta scenarii de test in Java\r\n- interactioneaza cu echipele de dezvoltatori \r\n- dezvolta si intretine scenarii pentru testarea automata a produselor\r\n- dezvolta si intretine platforma si mediul de testare\r\n- administreaza mediul de testare\r\n\r\nCerinte:\r\n- absolvent al unei facultati de profil \r\n- cunostinte de baza programare Java\r\n- cunostinte sisteme de operare UNIX-like (instalare, configurare, operare, remote control)\r\n- experienta in utilizarea de metode automate de testare si scripting reprezinta un plus\r\n- competente Windows si Unix, \r\n- spirit de echipa, initiativa, autonomie, flexibilitate, bune abilitati de comunicare si organizare, logica, atentie pentru detalii\r\n\r\nOferta: \r\n- mediu dinamic si placut\r\n- pachet salarial atractiv, tichete de masa, asigurare medicala privata\r\n- training-uri, certificari, perspective reale de promovare\r\n- deplasari in strainatate\r\n\r\n', 'Viziteaza-ne la www.axway.com sau email la lfivan@axway.com ', 'Axway Romania', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(65, 1, 'SENIOR TESTER', 'Essential skills:\r\n\r\nâ€¢Good experience in functional testing;\r\nâ€¢Good knowledge of the software testing lifecycle;\r\nâ€¢Strong analytical and organizational skills; attention to details;\r\nâ€¢Ability to understand business processes;\r\nâ€¢Strong English language skills (both oral and written).\r\n\r\nDesirable skills:\r\n\r\nâ€¢Skills in using Mercury Test Director\r\nâ€¢Experience/knowledge of telecom-specific CRM and billing systems\r\nâ€¢Wide use of test tools\r\n\r\nRESPONSABILITATI / BENEFICII:\r\n\r\nProject description\r\n\r\nWeâ€™re providing high-quality software testing services to one of the largest mobile telecommunications network companies in the world. Our main responsibilities consist in performing software testing throughout the whole system and system integration testing lifecycle for various CRM, Billing and Self-Care applications.\r\n\r\n\r\nYou will be required to:\r\n\r\nâ€¢Review and analyze documentation/specifications;\r\nâ€¢Contribute to the creation of test plans;\r\nâ€¢Identify, write and peer review test cases based on the specifications;\r\nâ€¢Identify and create test data;\r\nâ€¢Run, execute tests according to plan;\r\nâ€¢Identify and report defects; track and retest defects;\r\nâ€¢Provide constructive criticism; contribute to lessons learnt for future releases and projects. \r\n', 'Email luci.savu@endava.com ', 'ENDAVA', 'Cluj-Napoca ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(66, 1, 'tehnician service IT', 'CANDIDATUL IDEAL: \r\n\r\nCunostinte solide in domeniul IT â€“ hardware; \r\nCunostinte solide in configurarea si depanarea retelelor de calculatoare; \r\nCunostinte depanare sisteme electronice; \r\nCunoasterea limbii engleze la nivel mediu; \r\nAbilitati foarte bune de comunicare cu clientii si colegii; \r\nDinamic. \r\n\r\n\r\nRESPONSABILITATI / BENEFICII: \r\n\r\nExecuta operatiuni de instalare, mentenanta si depanare echipamente IT; \r\nAsigura suport tehnic si consultanta pentru clienti; \r\nOfera solutii tehnice impreuna cu echipa de vanzari; \r\nRespecta prevederile din sistemul calitatii implementat in cadrul firmei. \r\n\r\nBeneficii: \r\nMediu de lucru dinamic alaturi de o echipa de profesionisti; \r\nOportunitatea perfectionarii si promovarii; \r\nRecompensa materiala in concordanta cu nivelul profesional al ocupantului postului. \r\n\r\n', 'trimite CV la e-mail: resurse_umane@netland.ro ', 'Netland Computers', 'Ploiesti ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(67, 1, 'Security Software Tester and Supporter', 'Acunetix is an international software company specializing in web security scanning software. Web attacks are on the rise and traditional network security does not protect against them. Acunetix developed a Media Vulnerability Scanner that crawls a website and checks for vulnerabilities in web applications which often have a direct line into the company''s most valuable data assets. The Acunetix management team is backed by many years of experience in marketing and selling security software. Being a young, dynamic and growing company you will be assured of an exciting job opportunity with excellent career prospects.\r\n\r\nThis position requires extensive experience with software testing and knowledge of computer security software.\r\n\r\nYou will be in charge of handling support issues for customers worldwide whilst also coordinating and testing product releases. In addition, you will be required to write technical documentation and white papers, as well as track security blogs worldwide.\r\n\r\nYou will need to relocate to Cluj-Napoca.\r\n\r\nYou should have a good command of English language.\r\n\r\n', 'Trimite CV la email info@acunetix.com ', 'Acunetix ', 'Cluj Napoca', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(68, 1, 'Technical HelpDesk Assistant', 'Cautam persoane tinere, dinamice (disponibilitate de a calatori in tara sau in afara cca. 30% din timp), cu cunostinte medii de engleza sau franceza, pentru un client cu traditie in domeniul dezvoltarii de solutii expert in HR. \r\nCandidatul ideal trebuie sa aiba experienta in domeniul HelpDesk de cel putin 2 ani, cunostinte medii de administrare servere (MS SQL, MS Exchange, Active Directory), abilitati de comunicare si analiza peste medie si sa fie dispus sa se deplaseze (cand este cazul) la sediile clientilor pentru supervizarea proceselor de implementare / configurare / depanare a sistemelor dezvoltate de clientul nostru. \r\nOferim posibilitatea de a participa intr-un mediu dinamic, international, cu reale posibilitati de afirmare. \r\nVa rugam sa trimiteti CV-ul la bogdan@bobyte.ro , insotit de pretentiile salariale. Numai persoanele potrivite vor fi contactate', 'Trimiteti CV-ul la bogdan@bobyte.ro ', 'boBYTE Consulting', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(69, 5, 'System Administrator', 'Responsabilitati: \r\n- Asigura suportul si mentenanta retelei de calculatoare; \r\n- Asigura administrarea serverelor companiei; \r\n- Asigura extinderea, dezvoltarea si perfectionarea retelei de calculatoare. \r\n\r\nCerinte: \r\n- Cunostinte solide de instalare, configurare si administrare platforme Microsoft (AD, ISA, Exchange, TS, IIS, WSUS); \r\n- Cunostinte solide networking \r\n- Studii superioare cu specializare in informatica; \r\n- Experienta minima de 2 ani intr-o pozitie similara. \r\n\r\nConstituie avantaj Certificarile Microsoft. \r\n\r\n\r\n', 'trimite CV la e-mail: hr@rhs.ro ', 'RHS COMPANY ', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:23:36', 0, '0000-00-00 00:00:00'),
(70, 5, 'ADMINISTRATOR RETEA', '- Defineste un plan pentru intretinere PC-uri, imprimante \r\n- Tine evidenta echipamentelor hardware si solutiilor software \r\n- Defineste un plan pentru imbunatatirea timpului de raspuns la problemelor untilizatorilor \r\n- Definesteste procedura de achizitii echipamente IT \r\n- Ofera suport in instalarea unor programe, instalarea imprimantelor, resetarea de parole \r\n- Intocmeste si livreaza rapoarte lunare cu privire la pc-urilor, imprimantelor \r\n- Pastreaza in conditii optime echipamentele IT. \r\n', 'humanres@cpn.ro ', 'Sensident', 'BUCURESTI', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:23:36', 0, '0000-00-00 00:00:00'),
(71, 5, 'SYSTEM ADMINISTRATOR', 'CANDIDATUL IDEAL:\r\n\r\nRequirements:\r\nâ€¢Good system administration skills (Windows servers and Linux servers), good hardware skills (maintenance and upgrades);\r\nâ€¢Good networking skills, able to understand and enhance an existing topology;\r\nâ€¢Knowledge of Win 2000/2003 Server, Active Directory, Exchange 2003, IIS, Windows XP Pro, Linux/UNIX Redhat;\r\nâ€¢Responsible, dependable, well organized, quick learner, initiative;\r\nâ€¢Good English, written and spoken.\r\n\r\nRESPONSABILITATI / BENEFICII:\r\n\r\nResponsibilities:\r\nâ€¢Manages the networks (network requirements, servers, switches and specific equipment in general);\r\nâ€¢Assures company data integrity by developing, implementing and maintaining back-up policies;\r\nâ€¢Manages new versions of software applications, upgrades the systems, and monitors the use of applications on the workstations and servers;\r\nâ€¢Plans and implements system security policy, to include firewalls, host and client access, file permissions, and user accounts;\r\nâ€¢Maintains currency of knowledge with respect to relevant state-of-the-art technology, equipment, and/or systems;\r\nâ€¢Ensure trouble-free running of Endava production systems;\r\nâ€¢Support Endava employees and customers in using the software and hardware equipments;\r\nâ€¢Participate in hardware/software evaluation and purchasing.\r\n\r\nDESCRIEREA COMPANIEI SAU A JOBULUI:\r\n\r\nEndava is a privately owned IT services organization with professional staff operating from offices across Europe - London, Oxfordshire, Bucharest - Romania, Cluj-Napoca - Romania, Iasi â€“ Romania, Chisinau â€“ Moldova and Cahul - Moldova. Our aim is to assist our customers in translating their strategic business initiatives into coherent, successful, IT change programs that deliver quantifiable business benefit and ensure that our customers are able to compete in their markets of choice. We are specialists in the delivery and operation of IT based Business Solutions and Secure Messaging Systems in the international Financial ', 'Email luci.savu@endava.com ', 'ENDAVA', 'Cluj-Napoca', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:23:36', 0, '0000-00-00 00:00:00'),
(72, 2, 'Grafician', 'Descrierea postului: \r\nRealizare de grafica WEB: \r\n- concepere si grafica materiale de prezentare ( pliante, brosuri, cataloage, afise, newslettere); \r\n- procesare si colaje de imagini; \r\n- verificarea tehnica si optimizarea machetelor in vederea tiparirii. \r\n\r\nCerinte: \r\n- experienta in lucru cu aplicatiile grafice: Adobe Photoshop, Adobe Ilustrator, CorelDraw, Adobe Indesign; \r\n- cunostinte HTML, Macromedia Flash, Macromedia Dreamwaver ( Constituie avantaj ); \r\n- experienta in ceea ce priveste propunerea si realizarea site-urile ( layout ); \r\n- experienta in realizarea logo-urilor, animatiilor flash si banerelor publicitare; \r\n- abilitati de intretinere si up-date la proiecte web existente; \r\n- respectarea dead-line-urilor; \r\n- cunosterea regulilor, standardelor si tiparelor de design; \r\n- persoana creativa, comunicativa, cu simt estetic dezvoltat; \r\n- capacitate de analiza, organizare si planificare; \r\n- capacitate de lucru in echipa. \r\n', 'trimite CV la e-mail: hr@rhs.ro ', 'RHS COMPANY', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:24:19', 0, '0000-00-00 00:00:00'),
(73, 2, 'Web Designer ', 'Web Designer pentru aplicatii web / web-like \r\n\r\nCerinte: \r\n\r\nCandidatul ideal trebuie sa indeplineasca urmatoarele cerinte: \r\n- HTML, CSS, DESIGN (Dreamweaver sau similar),javascript, \r\n- cunostintele de grafica (pentru crearea de icons,logo etc) \r\n- cunoasterea unui limbaj de scripting (server-side, client side) este un plus \r\n\r\n- limba engleza; \r\n- limba franceza este un plus \r\n- lucru in echipa, respectarea deadlineurilor \r\n\r\nOferta (bonusuri, beneficii): \r\n\r\nTraininguri de specialitate pentru noile tehnologii \r\n', 'Va rugam trimiteti cv la hr [at]newsystemdesign [dot] com ', 'New System Design', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:24:19', 0, '0000-00-00 00:00:00'),
(74, 3, 'Project Manager', 'Responsabilitati:\r\n- asigurarea respectarii standardelor tehnice stabilite pentru proiectul respectiv;\r\n- initierea si participarea la programele de instruire;\r\n- instruirea tehnica si integrarea angajatilor aflati in subordine;\r\n- asigurarea unei bune comunicari atat in interiorului echipei cat si in relatiile cu clientii;\r\n- implicarea pe parcursul intregului ciclu de dezvoltare a produsului.\r\n\r\nCerinte:\r\n- absolvent al unei facultati de profil \r\n- experienta minim 3 ani in coordonarea de proiecte;\r\n- cunoasterea foarte buna a limbii franceze; limba engleza constituie un avantaj;\r\n- aptitudini de organizare si comunicare atat la nivel individual cat si la nivel de echipa;\r\n- competente MS SQL-Server, ORACLE, C #, C++, Java, Visual C++, ASP, DHTML, HTML, J2EE, Java, Java Beans, JavaScript, JSP,XML, XSL\r\n\r\nOferta: \r\n- mediu dinamic si placut\r\n- pachet salarial atractiv, tichete de masa, asigurare medicala privata\r\n- training-uri, certificari, perspective reale de promovare\r\n- deplasari in strainatate\r\n\r\n', 'Viziteaza-ne la www.axway.com sau email la lfivan@axway.com ', 'Axway Romania', 'Bucuresti ', 1, '2007-12-15 12:00:00', '', '2008-01-06 07:23:54', 0, '0000-00-00 00:00:00'),
(75, 1, 'Programator ASP.NET si baze de date MS-SQL', 'CANDIDATUL IDEAL: \r\n\r\nCerinte: \r\n- baze de date Microsoft (sql server) \r\n- experienta in proiecte ASP.NET (C#) in aplicatii web \r\n- cunostinte HTML, CSS, XML, XSL, JavaScript, optional AJAX; \r\n- arhitectura aplicatii web; \r\n\r\nRESPONSABILITATI / BENEFICII: \r\nRealizarea de proiecte complex, intr-o echipa tanara, cu initiativa. \r\nBonusuri si compensatii pe masura implicarii. \r\nProgram de lucru flexibil. \r\n\r\nDESCRIEREA COMPANIEI SAU A JOBULUI: \r\n\r\nVirtualSoft (www.virtual-soft.ro) are ca activitate principala proiectarea si realizarea aplicatiilor software, in special solutii web-based, folosind tehnologii de ultima generatie Mssql si .net, care gestioneaza sisteme de date multiple in timp real. \r\n\r\nProiecte proprii: www.zoom-it.ro \r\n', 'trimite email la: office@virtual-soft.ro ', 'SC VirtualSoft SRL', 'Bucuresti ', 1, '2007-12-27 12:00:00', '', '2008-01-06 07:21:40', 0, '0000-00-00 00:00:00'),
(76, 1, 'Depanator PC Intretinere IT Hardware &amp; Software, Retelistica', '&lt;b&gt; ceva &lt;/b&gt;&lt;br&gt;\r\n&lt;i&gt; alveca &lt;/i&gt;&lt;br&gt;\r\ncedfadfad\r\n\r\n', 'Trimiteti cv&#039;ul la cmc@cmcmultimedia.ro ', 'CMC Multimedia', 'Bucuresti ', 1, '2007-12-27 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(77, 1, 'Software Quality Engineer', 'Position Purpose:\r\n• We are looking for a dedicated, self motivated, highly skilled Software Quality Engineer to join our team for building high-end, highly scalable Web and transactional applications.\r\n• Successful candidates will have a solid Quality Assurance &amp; Development background (Java, NET, C++, Flash) with the ability and passion to ensure development codebases are of high quality.\r\n• Knowledge of automated test tools.\r\n• BSc in Computer Science or equivalent demonstrated knowledge\r\n• Understanding of browser compatibility issues\r\n• Proficiency in test case generation techniques: equivalence partitioning, boundary value analysis etc\r\n• Experience of different software development methods\r\n\r\n\r\n\r\n• Work as integral part of the development teams to ensure codebase is of the highest quality\r\n• Help developers to work within a test driven development environment\r\n• Ensure test suite is comprehensive, automated and repeatable\r\n• Maintain continuous integration system\r\n• Ensure end to end integration tests are run nightly\r\n• Work with Product Owner to ensure that the business and operational requirements have valid, automated, tests\r\n\r\n\r\n\r\nAbout Xoomworks\r\n\r\nXoomworks is a professional services company focused on application, integration and managed services. Some areas that we cover are eGaming, Procurement, Spend Management and Finance.\r\n\r\nXoomworks was founded in 2000 by former partners of Deloitte Consulting who wanted to introduce a new style of IT services partner, combining the business consulting with technical consulting in order to successfully deliver solutions to large and mid-sized companies.\r\n\r\nCulturally we combine the technical and business expertise of a Big 4 consultancy with the ethos and innovation of a small business.\r\n\r\nWe are looking for people who are interested in working with the latest hardware, latest technologies and latest development processes on mission critical application. We care about our employees and we invest in them.', 'If interested please send an English version of your resume to pdro@xoomworks.com', 'SC Xoomworks Ro SRL', 'Cluj-Napoca', 1, '2007-12-27 12:00:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(91, 1, 'Design Engineer', 'Main tasks:\r\n• Design works in CAD for bracket design and for general packaging issues\r\n• Preparations of customer drawings\r\n• Tolerance studies;\r\n• Support for preparation of product specifications and Design-FMEA\r\n\r\n\r\nQualifications required:\r\n• Technical graduate with a major in mechanics / mechanics related lines of study\r\n• Computer Aided Design (C.A.D.) experience - at least one project in Catia or similar software (e.g. Pro Engineer)\r\n• Fluent English\r\n\r\n', ' or by fax: 0369/433.069  Take the first step and fill in the online application at career@contiautomotive.com', 'Continental AG', 'Sibiu', 1, '2007-12-28 12:24:00', '', '2009-04-11 09:16:31', 0, '0000-00-00 00:00:00'),
(92, 0, 'Programator PHP MySQL', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:27:02', 0, '0000-00-00 00:00:00'),
(93, 0, 'Programator PHP MySQL', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:27:07', 0, '0000-00-00 00:00:00'),
(94, 0, 'Programator PHP MySQL', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:29:49', 0, '0000-00-00 00:00:00'),
(95, 0, 'Programator PHP MySQL', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:30:18', 0, '0000-00-00 00:00:00'),
(96, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:30:44', 0, '0000-00-00 00:00:00'),
(97, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:31:28', 0, '0000-00-00 00:00:00'),
(98, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:31:48', 0, '0000-00-00 00:00:00'),
(99, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:32:12', 0, '0000-00-00 00:00:00'),
(100, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:32:57', 0, '0000-00-00 00:00:00'),
(101, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:33:20', 0, '0000-00-00 00:00:00'),
(102, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:33:40', 0, '0000-00-00 00:00:00'),
(103, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:33:44', 0, '0000-00-00 00:00:00'),
(104, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:33:55', 0, '0000-00-00 00:00:00'),
(105, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:34:18', 0, '0000-00-00 00:00:00'),
(106, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:34:36', 0, '0000-00-00 00:00:00'),
(107, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:34:53', 0, '0000-00-00 00:00:00'),
(108, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Nobody', 'Iasi', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:35:33', 0, '0000-00-00 00:00:00'),
(109, 0, 'Programator PHP MySQL Javascript', 'Descriere job php', 'Da telefon', 'Valentin Bora', 'Bacau', 0, '0000-00-00 00:00:00', '', '2009-04-13 17:36:12', 0, '0000-00-00 00:00:00');

-- --------------------------------------------------------

--
-- Table structure for table `plugin_data`
--

DROP TABLE IF EXISTS `plugin_data`;
CREATE TABLE IF NOT EXISTS `plugin_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `plugin_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `option_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `option_value` varchar(4096) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `option_name` (`option_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=4 ;

--
-- Dumping data for table `plugin_data`
--

INSERT INTO `plugin_data` (`id`, `plugin_name`, `option_name`, `option_value`) VALUES
(2, 'Twitter', 'softos', 'valuos'),
(3, 'Twitter', 'softos', 'valuos');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `realname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
  `password_salt` varchar(51) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `username` (`username`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC AUTO_INCREMENT=3 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`ID`, `username`, `realname`, `password`, `password_salt`) VALUES
(2, 'bvali', 'Valentin Bora', '91096b8ec93efb8655604f1b39802eb4', 'rokfsfmuouklcywmxsctwsvpnagxtgbycmoqnhjglvusxqmhhv');
